### ISSUE TITLE
About number of generated rooms in Bedroom

### ISSUE THREAD

**Issue by yuxiaoguo** [ManyiLi12345/GRAINS#1]
Hi, author:

I am trying to generate the traning samples with guidance and SUNCG (downloaded from official website previously). From the paper, there are totally 18763 scenes of type "Bedroom". However, after running the first step (in your guidance), we generated 40K+ scenes of type "Bedroom". Do you have any hints about the misalginment size? Or there exists some other filters in later steps to finally decrease the number of scenes as you reported in paper.

Thanks!

**Comment by agp-ka32** [comment]
> Hi, author:
> 
> I am trying to generate the traning samples with guidance and SUNCG (downloaded from official website previously). From the paper, there are totally 18763 scenes of type "Bedroom". However, after running the first step (in your guidance), we generated 40K+ scenes of type "Bedroom". Do you have any hints about the misalginment size? Or there exists some other filters in later steps to finally decrease the number of scenes as you reported in paper.
> 
> Thanks!

Hi,
The total number of scenes in SUNCG dataset is around 45000 and each scene consists of rooms belonging to different scene-types, ex: bedroom, living room, office, dining etc. That is, one sene can have multiple rooms. We extracted rooms belonging to the type "bedrooms". And we chose 18763 bedrooms. You can select any 18763 bedroom scenes; it should still be possible to reproduce our results atleast closely, if not exactly.

**Comment by yuxiaoguo** [comment]
Thanks! That's really helpful. 

One more question, why you didn't use all bedrooms but selected partial data (18763 rooms)? Is there any consideration on algorithm stability? Or it just a legacy choice.

**Comment by agp-ka32** [comment]
> Thanks! That's really helpful.
> 
> One more question, why you didn't use all bedrooms but selected partial data (18763 rooms)? Is there any consideration on algorithm stability? Or it just a legacy choice.

Most welcome :)
No particular reason for selecting partial data (i.e, 18763 bedrooms). Timing (in terms of getting some results) was important and 18K scenes are more than enough for learning a Recursive Neural Network.
In data-driven techniques, the more data you have, the better it is.  Bottom line: We just stopped after we had these many bedroom-scenes and moved on to other room types.
