### ISSUE TITLE
Same scenes

### ISSUE THREAD

**Issue by zcoo** [ManyiLi12345/GRAINS#2]
I follow the training and test step but find that the 1000 generated scenes from test are similar without much diversity. Is there any mistake I made that cause the result? Thank you for answering.

**Comment by zcoo** [comment]
![res](https://user-images.githubusercontent.com/24472807/61266559-d9be4780-a7c6-11e9-901a-307a528aadf9.png)
For example the picture 3,4,6,9,11 are similar. And 1,7,12 are similar.

**Comment by ManyiLi12345** [comment]
Hi @zcoo, thank you for your interest.
This is a screenshot of our generated scenes. We haven't encountered this problem in our experiments. 
![lll](https://user-images.githubusercontent.com/32686965/62003787-0af51c80-b0d1-11e9-923f-c945fa89f1be.JPG)
Also, we noticed that many of your generated scenes have more than 4 walls. This is very rare in our experiment results (about one in a hundred).
Did you alter any parameter? How many epochs did you run?

**Comment by wwwjs** [comment]
sorry, but I can not get the original Dataset, the link is to https://www.princeton.edu/ not http://suncg.cs.princeton.edu/. And how can I get the original Dataset?
