### ISSUE TITLE
original Dataset

### ISSUE THREAD

**Issue by wwwjs** [ManyiLi12345/GRAINS#3]
sorry, but I can not get the original Dataset, the link is to https://www.princeton.edu/ not http://suncg.cs.princeton.edu/. And how can I get the original Dataset?

**Comment by ManyiLi12345** [comment]
There is a legal dispute with SUNCG dataset. I'm afraid this dataset is not available right now. And that's why we have deleted all our pre-trained models and the related data files.

**Comment by wwwjs** [comment]
Are there alternative datasets?

**Comment by ManyiLi12345** [comment]
Hi @wwwjs , so far we are not aware of any dataset comparable to SUNCG. This is now a problem.
