### ISSUE TITLE
In./5-reconVAE/readMetafiles.m,can't find v1_ModelCategoryMapping_new_1_babybeds2plants.csv

### ISSUE THREAD

**Issue by xyx18061932** [ManyiLi12345/GRAINS#9]
In./5-reconVAE/readMetafiles.m, the fifth line,  [model_category_title, model_category_body ] = read_csv('v1_ModelCategoryMapping_new_1_babybeds2plants.csv');
can't find the 'v1_ModelCategoryMapping_new_1_babybeds2plants.csv' .

**Comment by ManyiLi12345** [comment]
This function is to process the SUNCG files to obtain the required object label and other information. I have uploaded the processed file in ./0-data/object_per_label/. So this function will not be called when running the code. Please check these uploaded files.
